baseURL = "http://hautzenberger.at/"
languageCode = "en-us"
title = "hautzenberger.at"
theme = "hautzenbergerat"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Photography"
    url = "/posts/photography"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/posts/blog/"
    weight = 3
  [[menu.main]]
    name = "Me"
    url = "/me"
    weight = 4
